### PR TITLE
Bump MathProgBase upper bound

### PR DESCRIPTION
**Pull request by mlubin**

### CODE REVIEW

**Comment by stevengj** [comment]
Why do we even have an upper bound?

**Comment by mlubin** [comment]
MPB occasionally makes breaking API changes.

**Comment by stevengj** [comment]
So does every package, but putting upper bounds in REQUIRE is rare. It seems easier to fix dependent packages when they break than to continually update the upper bound (or force users to use an out-of-date package).

**Comment by mlubin** [comment]
There are 20+ packages that depend on MathProgBase within the JuliaOpt ecosystem, and more beyond that. I would find it impossible to hide breakage from users without upper bounds.

**Comment by blegat** [comment]
Without an upper bound, during the time the new MPB is released and the dependent package is fixed, everyone doing `Pkg.update()` will have a broken package. Even it is only a few hours, it does not seem desirable.

**Pull request merged**
