### PR TITLE
revision of pr for julia 0.7 deprecation warnings

### PR DESCRIPTION
**Pull request by mcreel**
This PR incorporates the suggestions made regarding the previous PR, except one.

### CODE REVIEW

**Comment by stevengj** [comment]
In the future you should try to update an existing PR rather than opening a new one.  (You can do a forced push to the old branch to replace old commits.)

**Comment by stevengj** [comment]
Which suggestion did you not take?

**Comment by mcreel** [comment]
It was this one:

```
src/NLopt.jl
     f::Function
     o::Any # should be Opt, but see Julia issue #269
 end
 
-type Opt
+mutable struct Opt
     opt::_Opt
 
     # need to store callback data for objective and constraints in
     # Opt so that they aren't garbage-collected.  cb[1] is the objective.
     cb::Vector{Callback_Data}
```
 @stevengj
stevengj 16 hours ago  Contributor
This probably should be changed to Ref{Callback_Data}

**Comment by stevengj** [comment]
Why not?

**Comment by stevengj** [comment]
superseded by #114

**Comment by stevengj** [comment]
Oh, nevermind, it actually needs to be a vector since it can have multiple elements.

**Comment by stevengj** [comment]
(Note that #114 incorporated the commits here from @mcreel — thanks!)

**Pull request closed without merging**
