### PR TITLE
Don't call jac_structure without constraints

### PR DESCRIPTION
**Pull request by abelsiqueira**
Related to https://github.com/JuliaOpt/Ipopt.jl/pull/71

### CODE REVIEW

**Comment by abelsiqueira** [comment]
CC @mlubin

**Comment by stevengj** [comment]
LGTM.

**Comment by tkelman** [comment]
This needs tagging, the tests on the released version have been failing since december https://github.com/JuliaOpt/MathProgBase.jl/pull/133

**Comment by tkelman** [comment]
Looks like attobot's enabled here, I'm going to tag.

**Pull request merged**
