### PR TITLE
Use package on FreeBSD.

### PR DESCRIPTION
**Pull request by yurivict**

### CODE REVIEW

**Comment by stevengj** [comment]
Should probably bump the REQUIRES file to Julia 0.6 and update the CI tests.

**Comment by yurivict** [comment]
I updated julia version. Not sure how to update CI tests.

**Comment by stevengj** [comment]
Look in the `.travis.yml` and `appveyor.yml` files and delete the tests for 0.4 and 0.5.

**Comment by yurivict** [comment]
Done.

**Pull request merged**
